/* Generated by AN DISI Unibo */
/*
This code is generated only ONCE
*/
package it.unibo.robot_adapter;

import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Robot_adapter extends AbstractRobot_adapter {
	public Robot_adapter(String actorId, QActorContext myCtx, IOutputEnvView outEnvView) throws Exception {
		super(actorId, myCtx, outEnvView);
	}

	/*
	 * ADDED BY THE APPLICATION DESIGNER
	 */
	@Override
	public void aroundPostStop() {
		it.unibo.robotadapter.allRobots.terminate(this);
		super.aroundPostStop();
	}
}
