/* Generated by AN DISI Unibo */ 
/*
This code is generated only ONCE
*/
package it.unibo.robot_planner;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Robot_planner extends AbstractRobot_planner { 
	public Robot_planner(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
		super(actorId, myCtx, outEnvView);
	}
/*
 * ADDED BY THE APPLICATION DESIGNER	
 */
}
