/* Generated by AN DISI Unibo */ 
/*
This code is generated only ONCE
*/
package it.unibo.world_observer;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class World_observer extends AbstractWorld_observer { 
	public World_observer(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
		super(actorId, myCtx, outEnvView);
	}
/*
 * ADDED BY THE APPLICATION DESIGNER	
 */
	@Override
	public void aroundPostStop() {
		it.unibo.utils.mqttUtil.disconnect(this);
		super.aroundPostStop();
	}
}
