/* Generated by AN DISI Unibo */
/*
This code is generated only ONCE
*/
package it.unibo.robot_retriever_mind;

import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Robot_retriever_mind extends AbstractRobot_retriever_mind {
	public Robot_retriever_mind(String actorId, QActorContext myCtx, IOutputEnvView outEnvView) throws Exception {
		super(actorId, myCtx, outEnvView);
	}
	/*
	 * ADDED BY THE APPLICATION DESIGNER
	 */
}
